packages:
  - 'packages/*'
  - 'playground'

overrides:
  vite: npm:@voidzero-dev/vite-plus-core@latest
  vitest: 4.1.10

onlyBuiltDependencies:
  - vue-demi

allowBuilds:
  '@parcel/watcher': true
  vue-demi: true
