export const fontFamilyOptions = [
  { value: 'Alibaba PuHuiTi', label: '阿里巴巴普惠体', subsets: ['Thin', 'Light', 'Regular', 'RegularL3', 'SemiBold', 'Medium', 'Bold', 'ExtraBold', 'Heavy', 'Black'] }
  // { value: 'Alimama ShuHeiTi', label: '阿里巴巴书黑体' },
  // { value: 'ZhanKu WenYiTI', label: '站酷文艺体' },
  // { value: 'SiYuan SongTi', label: '思源宋体' },
  // { value: 'SiYuan HeiTi', label: '思源黑体' },
  // { value: 'Plus Jakarta Sans', label: 'Plus Jakarta Sans' },
  // { value: 'DM Sans', label: 'DM Sans' },
  // { value: 'HarmonyOS Sans', label: 'HarmonyOS Sans' },
  // { value: 'OPPO Sans', label: 'OPPO Sans' },
  // { value: 'Mi Sans', label: 'Mi Sans' },
  // { value: 'Noto Sans SC', label: 'Noto Sans SC' },
  // { value: 'Resource Han Rounded', label: 'Resource Han Rounded' },
  // { value: 'SiYuan RouHeiTi', label: '思源肉黑体' },
  // { value: 'Tsanger YuYangTi', label: '藏文圆体' },
  // { value: 'ZCOOL GDH', label: '站酷高端黑' },
  // { value: 'ZCOOL Kuhei', label: '站酷酷黑' },
  // { value: 'Swei Spring SongTi', label: 'Swei Spring SongTi' },
  // { value: 'Vonwaon Bitmap', label: 'Vonwaon Bitmap' },
  // { value: 'Youshe Header Heiti', label: 'Youshe Header Heiti' },
  // { value: 'Pangmenzhengdao Header', label: 'Pangmenzhengdao Header' },
  // { value: 'Pangmenzhengdao Light', label: 'Pangmenzhengdao Light' },
  // { value: 'Wendaochao Heiti', label: 'Wendaochao Heiti' },
  // { value: 'Inter', label: 'Inter' },
  // { value: 'Roboto', label: 'Roboto' },
  // { value: 'Yellowtail', label: 'Yellowtail' },
  // { value: 'open sans', label: 'open sans' },
  // { value: 'D-DIN-PRO', label: 'D-DIN-PRO' },
  // { value: '-apple-system', label: '-apple-system' },
  // { value: 'pingFang SC', label: '苹方' },
  // { value: 'helvetica neue', label: 'Helvetica Neue' },
  // { value: 'stheiti', label: '华文细黑' },
  // { value: 'microsoft yahei', label: '微软雅黑' },
  // { value: 'tahoma', label: 'Tahoma' },
  // { value: 'simsun', label: '宋体' },
] as const
